# Generated by Django 5.1.2 on 2024-10-10 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEmpresa', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.TextField()),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_expiracion', models.DateField(blank=True)),
                ('es_activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CuponCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cupones.cliente')),
                ('cupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cupones.cupon')),
            ],
        ),
        migrations.CreateModel(
            name='CuponUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtenido', models.DateTimeField(auto_now_add=True)),
                ('usado', models.BooleanField(default=False)),
                ('cupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cupones.cupon')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cupones.usuario')),
            ],
        ),
    ]
